---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.app.namespace | default "default" }}
  name: {{ .Values.app.name }}
  labels:
    name: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.app.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 40%
  progressDeadlineSeconds: 300
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        env: test
        name: {{ .Values.app.name }}
        admission.datadoghq.com/enabled: 'true'
        tags.datadoghq.com/env: "test"
        tags.datadoghq.com/service: "xd-trial"
        tags.datadoghq.com/version: {{ .Values.image.tag }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.app.image_pull_policy | default "IfNotPresent" }}
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_LOGS_INJECTION
              value: "true"
          envFrom:
          - secretRef:
              name: {{ .Values.app.name }}
          ports:
            - containerPort: {{ .Values.app.port }}